name: Test Jira Plugin

on:
  workflow_dispatch:  # ط§ط¬ط±ط§غŒ ط¯ط³طھغŒ
#   push:
#     branches: [ main ]
#   pull_request:       # طھط±غŒع¯ط± ط®ظˆط¯ع©ط§ط± ط¨ط§ PR
#     branches: [ main ]

jobs:
  test-jira:
    runs-on: ubuntu-22.04  # Ubuntu 22.04 LTS
    
    steps:
      - name: Check Ubuntu version
        run: |
          lsb_release -a
          uname -a

