name: Test Jira Plugin

on:
  workflow_dispatch:  # اجرای دستی
#   push:
#     branches: [ main ]
#   pull_request:       # تریگر خودکار با PR
#     branches: [ main ]

jobs:
  test-jira:
    runs-on: ubuntu-22.04  # Ubuntu 22.04 LTS
    
    steps:
      - name: Check Ubuntu version
        run: |
          lsb_release -a
          uname -a
